// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.gestion_reservations_hotels.stubs;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reservation.Empty)
    com.google.protobuf.MessageOrBuilder {
}
