// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.gestion_reservations_hotels.stubs;

public interface ChambreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reservation.Chambre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string type_chambre = 2;</code>
   * @return The typeChambre.
   */
  java.lang.String getTypeChambre();
  /**
   * <code>string type_chambre = 2;</code>
   * @return The bytes for typeChambre.
   */
  com.google.protobuf.ByteString
      getTypeChambreBytes();

  /**
   * <code>double prix = 3;</code>
   * @return The prix.
   */
  double getPrix();

  /**
   * <code>bool disponible = 4;</code>
   * @return The disponible.
   */
  boolean getDisponible();
}
