// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.gestion_reservations_hotels.stubs;

public interface ReservationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reservation.ReservationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .reservation.ReservationResponse reservations = 1;</code>
   */
  java.util.List<com.example.gestion_reservations_hotels.stubs.ReservationResponse> 
      getReservationsList();
  /**
   * <code>repeated .reservation.ReservationResponse reservations = 1;</code>
   */
  com.example.gestion_reservations_hotels.stubs.ReservationResponse getReservations(int index);
  /**
   * <code>repeated .reservation.ReservationResponse reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .reservation.ReservationResponse reservations = 1;</code>
   */
  java.util.List<? extends com.example.gestion_reservations_hotels.stubs.ReservationResponseOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .reservation.ReservationResponse reservations = 1;</code>
   */
  com.example.gestion_reservations_hotels.stubs.ReservationResponseOrBuilder getReservationsOrBuilder(
      int index);
}
