// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.gestion_reservations_hotels.stubs;

public final class ReservationProto {
  private ReservationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_ReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_ReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_ReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_ReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_DeleteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\022\013reservation\"\007\n\005Empt" +
      "y\" \n\022ReservationRequest\022\n\n\002id\030\001 \001(\003\"q\n\023R" +
      "eservationResponse\022\n\n\002id\030\001 \001(\003\022\023\n\013client" +
      "_name\030\002 \001(\t\022\023\n\013room_number\030\003 \001(\005\022\022\n\nstar" +
      "t_date\030\004 \001(\t\022\020\n\010end_date\030\005 \001(\t\"N\n\024Reserv" +
      "ationsResponse\0226\n\014reservations\030\001 \003(\0132 .r" +
      "eservation.ReservationResponse\"j\n\030Create" +
      "ReservationRequest\022\023\n\013client_name\030\001 \001(\t\022" +
      "\023\n\013room_number\030\002 \001(\005\022\022\n\nstart_date\030\003 \001(\t" +
      "\022\020\n\010end_date\030\004 \001(\t\"v\n\030UpdateReservationR" +
      "equest\022\n\n\002id\030\001 \001(\003\022\023\n\013client_name\030\002 \001(\t\022" +
      "\023\n\013room_number\030\003 \001(\005\022\022\n\nstart_date\030\004 \001(\t" +
      "\022\020\n\010end_date\030\005 \001(\t\"!\n\016DeleteResponse\022\017\n\007" +
      "success\030\001 \001(\0102\317\003\n\022ReservationService\022U\n\016" +
      "GetReservation\022\037.reservation.Reservation" +
      "Request\032 .reservation.ReservationRespons" +
      "e\"\000\022M\n\022GetAllReservations\022\022.reservation." +
      "Empty\032!.reservation.ReservationsResponse" +
      "\"\000\022^\n\021CreateReservation\022%.reservation.Cr" +
      "eateReservationRequest\032 .reservation.Res" +
      "ervationResponse\"\000\022^\n\021UpdateReservation\022" +
      "%.reservation.UpdateReservationRequest\032 " +
      ".reservation.ReservationResponse\"\000\022S\n\021De" +
      "leteReservation\022\037.reservation.Reservatio" +
      "nRequest\032\033.reservation.DeleteResponse\"\000B" +
      "C\n-com.example.gestion_reservations_hote" +
      "ls.stubsB\020ReservationProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_reservation_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reservation_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_reservation_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_reservation_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_ReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_reservation_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_reservation_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_ReservationResponse_descriptor,
        new java.lang.String[] { "Id", "ClientName", "RoomNumber", "StartDate", "EndDate", });
    internal_static_reservation_ReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_reservation_ReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_ReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_reservation_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_reservation_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_CreateReservationRequest_descriptor,
        new java.lang.String[] { "ClientName", "RoomNumber", "StartDate", "EndDate", });
    internal_static_reservation_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_reservation_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Id", "ClientName", "RoomNumber", "StartDate", "EndDate", });
    internal_static_reservation_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_reservation_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_DeleteResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
